---
title: "Random subsampling: an approach to mapping very large evidence bases"
format: gfm
editor: visual
---

[Neal R Haddaway](https://github.com/nealhaddaway) 

[Matthew Grainger](https://github.com/DrMattG)

[Sini Savilaakso](https://www.linkedin.com/in/sini-savilaakso-21624564/)

Abstract

Systematic mapping is essential for cataloguing evidence, but the near-exponential growth in academic publishing, especially in environmental science, has made comprehensive mapping increasingly resource-intensive. While Artificial Intelligence is often proposed as a solution, it frequently struggles with the broad, non-core topics characteristic of expansive maps. This paper introduces a novel "random subsampling" methodology designed to produce reliable evidence syntheses when time or budgets are limited. The approach involves breaking deduplicated search results into random blocks—such as 20% increments—and processing each block entirely, from screening to data extraction, before moving to the next. This "map-first" strategy allows for a representative, albeit lower-resolution, assessment of the evidence base if project activities must terminate prematurely. We discuss the use of information saturation curves to determine sufficient resolving power. We validate the method through case studies, including aquaculture impacts and biodiversity monitoring in protected areas, alongside a real-world simulation identifying patterns across an intervention-outcome heatmap. Beyond managing workload, random subsampling offers significant risk-reduction benefits for contractual delivery and improves project efficiency by allowing for early data visualisation and refined eligibility criteria. Whilst the method precludes an immediate transition to a full systematic review without further targeted screening, it ensures that knowledge gaps and clusters are identified accurately. We conclude that random subsampling provides a pragmatic, robust framework for navigating the challenges of "big literature," ensuring that evidence maps remain a viable, insightful tool for researchers and commissioners alike.

Keywords

Evidence mapping, evidence synthesis, resource constraints, science policy, evidence informed decision making, scoping reviews
